
name: Build and Test

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Test
      run: mvn test
    - name: Package
      run: mvn clean package

#    Login to Docker Hub:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the image to Docker Hub:
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sachin3006/prescription-management:1.0.0


